Month 7/step 1
Dvdovina/react-stellar-burger pull request #1
Opened 2023-05-03 22:51 UTC by Dvdovina

Отправляю проект на первую промежуточную проверку.

2023-05-04 04:09 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с `propTypes`
-  Проект соответствует макету
- Логика отделена от верстки

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Верхняя и нижняя булки не должны скролиться. Скроляться только ингредиенты между ними
- Элементы хедера должны быть ссылками, а не просто текстом. Сейчас можно использовать просто тег `<a/>`.
- В propTypes нужно указывать содержимое объекта - props 
- Не у всех компонентов с пропсами есть `propTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-04 04:09 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-05-04 04:09 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const [current, setCurrent] = useState('buns');
**Можно лучше**
Дефолтное значeние - `buns` не соответствует ни одному из `value` у табов

2023-05-04 04:09 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    props: PropTypes.arrayOf(ingredientPropType).isRequired,
**Необходимо исправить**
Тут необходимо указывать содержимое объекта `props`. Т.е. в вашем случае тут должно быть 
`data: PropTypes.arrayOf(ingredientPropType).isRequired,`

2023-05-04 04:09 UTC, andryxxa93 commented on src/components/ingredient/ingredient.jsx
> +const Ingredient = (props) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-05-04 20:46 UTC, Dvdovina commented
Добрый вечер, внесла правки после первого промежуточного ревью. Отправляю на второе промежуточное ревью.

2023-05-05 06:41 UTC, andryxxa93 commented
**Необходимо исправить**
У `propTypes` необходимо добавлять `isRequired` и после закрывающей скобки функции `shape`. 

Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы.
Удачи!

2023-05-05 21:25 UTC, merged