Month 8/step 2
Dvdovina/react-stellar-burger pull request #4
Opened 2023-06-08 00:13 UTC by Dvdovina

Добрый вечер, отправляю вторую часть проекта на первое ревью.

2023-06-08 05:22 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Правильно используете RTK 
- Хорошая организация хранилища
- Раздельное хранение булок и ингредиентов в сторе

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если добавить одинаковые ингредиенты в конструктор, а потом удалить один, то удаляются все.
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-08 05:22 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const { ingredients, bun } = useSelector(
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-06-08 05:22 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
>      const mains = ingredients.filter((ingredient) => ingredient.type === 'main');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-06-08 16:24 UTC, Dvdovina commented
Спасибо! 

1. Устранила замечание - "Если добавить одинаковые ингредиенты в конструктор, а потом удалить один, то удаляются все." Одинаковые ингредиенты теперь удаляются по-отдельности.
2. "Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов." - Привела к начальному состоянию orderNumber и список ингредиентов в случае ошибки.
3. Обернула в хук useMemo ингредиенты.

2023-06-09 06:11 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-09 06:28 UTC, merged