Month 9/step 1
Dvdovina/react-stellar-burger pull request #5
Opened 2023-07-10 08:55 UTC by Dvdovina

Отправляю проект на первое ревью. Спасибо!

2023-07-10 11:17 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Проект запускается с ошибкой, нужно устранить ошибку: <https://disk.yandex.com/i/18KtPu_CFX43mw>;

- <https://disk.yandex.com/i/p3NqWMIV-oPmQg> - ошибок в консоли быть не должно;

- <https://disk.yandex.com/i/K7NbutsME8aJ4g> - неавторизованный пользователь не может отправлять заказ, после нажатия на кнопку, его должны перенаправить на страницу авторизации, а после авторизации.

- После обновления данных пользователя, луче скрывать кнопки.

- По чек-листу, требуется реализовать:

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям (Они не должны мелькать, в коде показал как исправить);

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

### **Сделает код лучше:**

- оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

  ```js
  <>
    <div>.....</div>
    <div>.....</div>
  </>
  ```

  <https://ru.reactjs.org/docs/fragments.html>

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +            <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
>          <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/ingredient/ingredient.jsx
>          <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/error-page/error-page.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/forgot-password/forgot-password.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/home/home.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/ingredient-page/ingredient-page.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/profile/profile.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/register/register.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/reset-password/reset-password.jsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +  }, [])
**Надо исправить:**

Тут не нужно делать никаких условий))

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +            await dispatch(submitOrder(cart));
**Можно лучше:**

await тут не нужен)

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/forgot-password/forgot-password.jsx
> +    })
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/pages/profile/profile.jsx
> +    const onSubmit = (values) => {
**Можно лучше:**

Лучше переименовать функцию, например в `updateUserInfo`

2023-07-10 11:17 UTC, ArslanMustafin commented on src/components/protected-route-element/protected-route-element.jsx
> +function Protected({ children, onlyUnAuth = false, }) {
**Надо исправить:**

тут вам нужно добавить проверку. Пока пользователь не прошёл авторизацию, то ничего не показывать.

Оптимальный пример компонента ProtectRoute:

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  // вот это вам нужно добавить
  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
> +    return fetchWithRefresh(`${config.loginUrl}`,
**Надо исправить:**

тут вроде бы простой fetch, это же логин)) у нас пока нету accessToken

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
> +                authorization: localStorage.getItem('accessToken')
тут тоже нужно убрать))

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
> +    return fetchWithRefresh(`${config.logoutUrl}`,
**Надо исправить:**

И тут тоже обычный fetch

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
> +    return fetchWithRefresh(`${config.passForgotUrl}`,
**Надо исправить:**

И тут тоже обычный fetch

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
> +    return fetchWithRefresh(`${config.passResetUrl}`,
**Надо исправить:**

И тут тоже обычный fetch

2023-07-10 11:17 UTC, ArslanMustafin commented on src/utils/api.js
>      return fetch(`${config.orderUrl}`,
**Надо исправить:**

тут нужно использовать fetchWithRefresh

2023-07-11 17:46 UTC, Dvdovina commented
Отправляю работу на второе ревью. Спасибо!

2023-07-12 03:50 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-12 03:50 UTC, ArslanMustafin commented on src/utils/api.js
> +                authorization: localStorage.getItem('accessToken')
**Надо исправить:**

Тут не нужно передавать accessToken

2023-07-12 03:50 UTC, ArslanMustafin commented on src/utils/api.js
>  const postOrder = (order, options = {}) => {
**Можно лучше:**

а вы уверено что параметр `options` тут нужен?

2023-07-12 05:43 UTC, merged